export const pageHeading =
  "On a quest to bring together and closer to you all things Organic";
export const headerImg = "./images/inner-header-bg.png";
export const list = [
  {
    key: "1",
    img: "./images/blogs/main_header.jpg",
    date: "August 21, 2023",
    title: "Health Benifits of Turmeric",
    buttonText: "Read more",
    buttonLink: "blogContent",
    fileName: "blog1",
  },
  {
    key: "2",
    img: "./images/blog-img1.png",
    date: "March 17, 2023",
    title: "Best guide to shopping for organic ingredients.",
    buttonText: "Read more",
    buttonLink: "blogContent",
    fileName: "blog2",
  },
  {
    key: "3",
    img: "./images/blog-img1.png",
    date: "March 17, 2023",
    title: "Best guide to shopping for organic ingredients.",
    buttonText: "Read more",
    buttonLink: "blogContent",
    fileName: "blog3",
  },
  {
    key: "4",
    img: "./images/blog-img1.png",
    date: "March 17, 2023",
    title: "Best guide to shopping for organic ingredients.",
    buttonText: "Read more",
    buttonLink: "blogContent",
    fileName: "blog4",
  },
  {
    key: "5",
    img: "./images/blog-img1.png",
    date: "March 17, 2023",
    title: "Best guide to shopping for organic ingredients.",
    buttonText: "Read more",
    buttonLink: "blogContent",
    fileName: "blog5",
  },
  {
    key: "6",
    img: "./images/blog-img1.png",
    date: "March 17, 2023",
    title: "Best guide to shopping for organic ingredients.",
    buttonText: "Read more",
    buttonLink: "blogContent",
    fileName: "blog6",
  },
  {
    key: "7",
    img: "./images/blog-img1.png",
    date: "March 17, 2023",
    title: "Best guide to shopping for organic ingredients.",
    buttonText: "Read more",
    buttonLink: "blogContent",
    fileName: "blog7",
  },
  {
    key: "8",
    img: "./images/blog-img1.png",
    date: "March 17, 2023",
    title: "Best guide to shopping for organic ingredients.",
    buttonText: "Read more",
    buttonLink: "blogContent",
    fileName: "blog8",
  },
  {
    key: "9",
    img: "./images/blog-img1.png",
    date: "March 17, 2023",
    title: "Best guide to shopping for organic ingredients.",
    buttonText: "Read more",
    buttonLink: "blogContent",
    fileName: "blog9",
  },
  {
    key: "10",
    img: "./images/blog-img1.png",
    date: "March 17, 2023",
    title: "Best guide to shopping for organic ingredients.",
    buttonText: "Read more",
    buttonLink: "blogContent",
    fileName: "blog10",
  },
  {
    key: "11",
    img: "./images/blog-img1.png",
    date: "March 17, 2023",
    title: "Best guide to shopping for organic ingredients.",
    buttonText: "Read more",
    buttonLink: "blogContent",
    fileName: "blog11",
  },
  {
    key: "12",
    img: "./images/blog-img1.png",
    date: "March 17, 2023",
    title: "Best guide to shopping for organic ingredients.",
    buttonText: "Read more",
    buttonLink: "blogContent",
    fileName: "blog12",
  },
];
