name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Git user information
        run: |
          git config --global user.name "chahalinder0007"
          git config --global user.email "chahal.inder0007@gmail.com"

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GH_TOKEN }}" | gh auth login --with-token

      - name: Install dependencies
        run: npm i

      - name: Run deploy script
        run: npm run deploy

      - name: Wait for 30 seconds
        run: sleep 120s

  update-gh-pages:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          token: ${{ secrets.GH_TOKEN }}

      - name: Create CNAME file
        run: echo "farmtoyoufresh.com" > CNAME

      - name: Set up Git user information
        run: |
          git config --global user.name "chahalinder0007"
          git config --global user.email "chahal.inder0007@gmail.com"

      - name: Commit and push changes
        run: |
          git add CNAME
          git commit -m "Add CNAME file"
          git push origin gh-pages